"use client";
import React, { useEffect, useState } from "react";
import axios from "axios";
import { useUser } from "@clerk/nextjs";
import Sidebar from "../components/Sidebar";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Sparkles, Download, Loader2, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";

const moodMap = { AWFUL: 1, BAD: 2, OK: 3, GOOD: 4, GREAT: 5 };

export default function SummaryPage() {
  const { user, isLoaded } = useUser();
  const [logs, setLogs] = useState([]);
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!user) return;
    const fetchLogs = async () => {
      try {
        const res = await axios.get("/api/moodlogs/all", {
          params: { userId: user.id },
        });

        const data = res.data
          .sort((a, b) => new Date(a.date) - new Date(b.date))
          .map((log) => {
            const moodKey = (log.mood || "").toUpperCase();
            return {
            date: new Date(log.date).toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
            }),
            moodValue: moodMap[moodKey] || log.moodValue || 0,
            moodLabel: log.mood || "N/A",
            sleep: log.sleepHours || 0,
            anxiety: log.anxietyLevel || 0,
            energy: log.energyLevel || 0,
            focus: log.focusLevel || 0,
            motivation: log.motivationLevel || 0,
            productivity: log.productivity || 0,
            social: log.socialInteraction || 0,
            notes: log.notes || "",
            morning: log.morningJournal || "",
            evening: log.eveningJournal || "",
          };
          });

        setLogs(data);
      } catch (err) {
        console.error("Failed to fetch mood logs:", err);
      }
    };
    fetchLogs();
  }, [user]);

  const handleGenerateSummary = async () => {
    if (!isLoaded) return;
    if (!user) {
      alert("Please log in first");
      return;
    }

    if (!logs.length) {
      alert("No mood logs found");
      return;
    }

    setLoading(true);
    setSummary("");

    try {
      const res = await axios.post("/api/moodlogs/generate-summary", {
        moodData: logs,
        userEmail: user.emailAddresses[0]?.emailAddress,
      });

      setSummary(res.data.summary || "No summary generated");
    } catch (error) {
      console.error("Error generating summary:", error);
      setSummary("Failed to generate summary. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([summary], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "MoodSummary.txt";
    link.click();
  };

  if (!isLoaded) return null;

  return (
    <div className="min-h-screen flex bg-background">
      <Sidebar />
      <div className="flex-1 p-6 md:p-8 overflow-auto">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-3xl font-bold tracking-tight mb-1">AI Summary</h1>
          <p className="text-muted-foreground">Get AI-powered insights from your mood data</p>
        </div>

        {/* Generate Button */}
        <Button
          onClick={handleGenerateSummary}
          disabled={loading}
          className="bg-gradient-to-r from-violet-600 to-teal-500 text-white rounded-xl px-6 py-5 shadow-lg hover:opacity-90 transition-all"
        >
          {loading ? (
            <><Loader2 size={18} className="animate-spin mr-2" /> Generating...</>
          ) : (
            <><Sparkles size={18} className="mr-2" /> Generate AI Summary</>
          )}
        </Button>

        {/* Summary Result */}
        {summary && (
          <div className="mt-8 bg-card border border-border/50 rounded-2xl overflow-hidden">
            <div className="p-6 border-b border-border/50 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-teal-500 flex items-center justify-center">
                  <FileText size={18} className="text-white" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold">Your Emotional Insight</h2>
                  <p className="text-sm text-muted-foreground">Generated by AI from your mood data</p>
                </div>
              </div>
              <Button
                onClick={handleDownload}
                variant="outline"
                className="rounded-xl"
              >
                <Download size={16} className="mr-2" /> Download
              </Button>
            </div>

            <div className="p-6">
              <div className="prose dark:prose-invert max-w-none prose-headings:tracking-tight prose-p:leading-relaxed prose-p:text-muted-foreground">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {summary}
                </ReactMarkdown>
              </div>
            </div>
          </div>
        )}

        {/* Empty state */}
        {!summary && !loading && (
          <div className="mt-12 text-center">
            <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-violet-100 to-teal-100 dark:from-violet-950/30 dark:to-teal-950/20 flex items-center justify-center mx-auto mb-4">
              <Sparkles size={32} className="text-violet-500" />
            </div>
            <h3 className="text-lg font-semibold mb-2">Ready to Generate</h3>
            <p className="text-muted-foreground text-sm max-w-md mx-auto">
              Click the button above to generate an AI-powered summary of your mood patterns, trends, and personalized recommendations.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
